# 1 - Inicialização

In [7]:
import pandas as pd

# 2 - Analisar o DF

In [11]:
df = pd.read_csv(r"C:\Users\andra\OneDrive\Área de Trabalho\sprint12\trending_by_time.csv")

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12343 entries, 0 to 12342
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   record_id       12343 non-null  int64
 1   region          12343 non-null  str
 2   trending_date   12343 non-null  str
 3   category_title  12343 non-null  str
 4   videos_count    12343 non-null  int64
dtypes: int64(2), str(3)
memory usage: 482.3 KB

In [13]:
df.head()

,record_id,region,trending_date,category_title,videos_count
0,1,France,2017-11-14 00:00:00.000000,Autos & Vehicles,8
1,2,France,2017-11-15 00:00:00.000000,Autos & Vehicles,2
2,3,France,2017-11-16 00:00:00.000000,Autos & Vehicles,6
3,4,France,2017-11-17 00:00:00.000000,Autos & Vehicles,8
4,5,France,2017-11-18 00:00:00.000000,Autos & Vehicles,4

In [17]:
# Verificar as categorias
categories = df['category_title'].unique()
categories

<StringArray>
[     'Autos & Vehicles',                'Comedy',             'Education',
         'Entertainment',      'Film & Animation',                'Gaming',
         'Howto & Style',                'Movies',                 'Music',
       'News & Politics',        'People & Blogs',        'Pets & Animals',
  'Science & Technology',                 'Shows',                'Sports',
              'Trailers',       'Travel & Events', 'Nonprofits & Activism']
Length: 18, dtype: str

In [18]:
# verificar as regiões
countries = df['region'].unique()
countries

<StringArray>
['France', 'India', 'Japan', 'Russia', 'United States']
Length: 5, dtype: str

In [19]:
# verificar se há valor repedido na coluna 'record_id'
df['record_id'].nunique()

12343

In [20]:
# Transformar a coluna 'trending_date' em datetime
df['trending_date'] = pd.to_datetime(df['trending_date'])

In [ ]:
# verificar se há duplicados
df.duplicated().sum()

np.int64(0)

# 3 - Criar colunas

In [22]:
# criar coluna de mês
df['month'] = df['trending_date'].dt.month

In [23]:
# criar coluna de semana
df['month'] = df['trending_date'].dt.isocalendar().week

In [24]:
# Criar coluna de dias da semana
df['week_days'] = df['trending_date'].dt.to_period('W')

In [25]:
df.head(3)

,record_id,region,trending_date,category_title,videos_count,month,week_days
0,1,France,2017-11-14,Autos & Vehicles,8,46,2017-11-13/2017-11-19
1,2,France,2017-11-15,Autos & Vehicles,2,46,2017-11-13/2017-11-19
2,3,France,2017-11-16,Autos & Vehicles,6,46,2017-11-13/2017-11-19

In [ ]:
# exportar DF analisado
df.to_csv('trending_by_time_v1.csv', index=True)